#! /bin/sh

bspc monitor -d I II III IV V VI


bspc config border_width 1
bspc config window_gap 18
bspc config split_ratio 0.5
bspc config bottom_padding 5
bspc config top_padding 23
bspc config auto_cancel true
bspc config history_aware_focus true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config apply_floating_atom true
/home/vandrex/.config/bspwm/panel/panel &
